name: CI

on:
  workflow_dispatch:
    inputs:
       dev:
          required: true
          description: select
          default: test2
env:
 ARRAY_VALUES: '{"first", "second"}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a single command using the runners shell
      - name: Run check
        if: ${{ contains(fromJSON(env.ARRAY_VALUES), github.event.inputs.dev) }}
      - name: Run success
        run: echo Hello, world!
