name: CI

on:
  workflow_dispatch:
    inputs:
       dev:
          required: true
          description: select
          default: test2

jobs:
  build:
    if: ${{ contains(fromJson('["test1", "test2"]'), github.event.inputs.dev) }}
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a single command using the runners shell
      - name: Run success
        run: echo Hello, world!
