name: CI

on:
  workflow_dispatch:
    inputs:
       dev:
          required: true
          description: select
          default: test2
env:
 ARRAY_VALUES: ("element1" "element2" "element3")

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $ARRAY_VALUES
