name: Deploy To Dev

on:
  workflow_dispatch:
    inputs:
      dev:
        required: true
        description: "Choose dev: optimus|starscream|thunderwing|mirage|bumblebee|grimlock"
        default: optimus

concurrency: build-${{ github.event.inputs.dev }}-${{ github.ref }}

env:
  AVAILABLE_DEVS: '["optimus", "starscream", "thunderwing", "mirage", "bumblebee", "grimlock"]'

jobs:
  k8s-to-dev:
    runs-on: [ self-hosted, supervisor-team ]
    needs: deploy-to-dev
    steps:
      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Kubernetes Deploy
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          inputs: '{"tag_sha": "${{ needs.deploy-to-dev.outputs.sha }}","environment":"${{ github.event.inputs.dev }}"}'