name: Update all devs

on:
  push:
    branches:
      - base

jobs:
  change-devs:
    strategy:
      matrix:
        branch: ["test", "test2", "test3" ]
    runs-on: ubuntu-latest
    steps:
      - name: "Change settings in dev: ${{ matrix.branch }}"
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Multi branch commit
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          inputs: '{
            "dev": "${{ matrix.branch }}",
            "replace-regex": "base-replaceable",
            "first-commit": "${{ github.event.before }}",
            "last-commit": "${{ github.event.after }}",
            "cherry-pick-options": "--strategy-option theirs"
          }'
