name: Test multi deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        branch: [ 'test2', 'test' ]
    runs-on: ubuntu-latest
    name: Change version
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          ref: ${{ matrix.branch }}
      - uses: peter-evans/rebase@v1
        with:
          token: ${{ secrets.APP_GITHUB_TOKEN }}
