name: Test multi deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        branch: [ 'test2', 'test' ]
    runs-on: ubuntu-latest
    name: Change version
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          ref: ${{ matrix.branch }}
#      - uses: everlytic/branch-merge@1.1.2
#        with:
#          target_branch: ${{ matrix.branch }}
#          github_token: ${{ secrets.APP_GITHUB_TOKEN }}
#          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
#         git merge --strategy-option theirs master
#      - name: Set commit author information
#        shell: bash
#        run: |
#          git config user.name "github-actions[bot]"
#          git config user.password ${{ secrets.APP_GITHUB_TOKEN }}
#      - name: Merge ${{ inputs.from }} with ${{ inputs.strategy }} strategy
#        shell: bash
#        run: |
#             git merge --strategy-option theirs origin/master
      - name: "Push changes from ${{ matrix.branch }} to origin"
        shell: bash
        run: |
          git config --global user.name 'romanprybudko@gmail.com'
          git config --global user.email 'romanprybudko@gmail.com'
          git config --global user.password ${{ secrets.APP_GITHUB_TOKEN }}
          git merge --strategy-option theirs master
          git push
