name: Test multi deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        branch: [ 'test2', 'test' ]
    runs-on: ubuntu-latest
    name: Change version
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          ref: ${{ matrix.branch }}
#      - uses: everlytic/branch-merge@1.1.2
#        with:
#          target_branch: ${{ matrix.branch }}
#          github_token: ${{ secrets.APP_GITHUB_TOKEN }}
#          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
      - uses: pr-mpt/actions-merge-branch@v2.1.0
        with:
          from: origin/master
          strategy: recursive -Xtheirs
