name: Test multi deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        branch: [ 'test2', 'test' ]
    runs-on: ubuntu-latest
    name: Change version
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          ref: master
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          target_branch: ${{ matrix.branch }}
          github_token: ${{ secrets.APP_GITHUB_TOKEN }}
