name: Multi branch commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        branch: ["test", "test2", "test3"]
    runs-on: ubuntu-latest
    name: Change version
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Set commit author information
        shell: bash
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Cherry pick
        shell: bash
        run: |
          if ! git cherry-pick ${{ github.event.before }}..${{ github.event.after }} -n --strategy-option theirs
          then
              echo "Auto Merge failed."
              git status
          else
              echo "Auto Merge successful."
          fi
      - name: Find and replace base branch
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: '(base-replaceable)'
          replacement: '${{ matrix.branch }}'
          flags: "g"
          exclude: ".github/workflows/multiple-commit.yml"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ matrix.branch }}
          commit_message: Dev update
          commit_user_name: romanprybudko@gmail.com
          commit_user_email: romanprybudko@gmail.com
          commit_author: romanprybudko@gmail.com <romanprybudko@gmail.com>
          commit_options: "--no-verify --signoff"
