name: Change devs settings

on:
  push:
    branches:
      - base

jobs:
  alteration:
    strategy:
      matrix:
        dev: [ "test", "test2", "test3" ]
    runs-on: ubuntu-latest
    name: Change version
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          ref: ${{ matrix.dev }}
          fetch-depth: 0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Cherry pick input commits
        shell: bash
        run: |
          if ! git cherry-pick ${{ github.event.before }}..${{ github.event.after }} -n
          then
              echo "Auto cherry-pick failed."
              git status
          fi
      - name: Find and replace base branch
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: '(base-replaceable)'
          replacement: '${{ matrix.devs }}'
          flags: "gm"
          exclude: ".github/workflows/multiple-commit.yml"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ matrix.dev }}
          commit_message: Alteration
          commit_user_name: prybudko
          commit_user_email: romanprybudko@gmail.com
          commit_options: "--no-verify --signoff"
